# Generated by Django 3.1.7 on 2024-08-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20240830_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('REC', 'Records'), ('CLO', 'Clothing'), ('POST', 'Posters'), ('MIS', 'Miscellaneous')], default='REC', max_length=5),
        ),
    ]
